### ISSUE TITLE
How to preview code (in the column to the left) in the column to the right

### ISSUE THREAD

**Issue by grahamperrin** [Wang-Yan-Hao/man_page_editor#6]
At <https://wang-yan-hao.github.io/man_page_editor/> I can, for example, load the code for bectl(8) **however** I see no way to preview: 

![image](https://github.com/Wang-Yan-Hao/man_page_editor/assets/192271/7631ab17-8ff8-450a-877d-44dfbfde68d6)

Maybe relevant: 

- the **Generate Content** button has no effect.

**Comment by Wang-Yan-Hao** [comment]
Thank you for your advice. It seems there are some issues with rendering certain macros in bectl(8). The current rendering engine, "Jorff.js," is not perfect at the moment. We will fix this page as soon as possible.

**Comment by Wang-Yan-Hao** [comment]
Fix the rendering error while edit bectl(8).

**Comment by grahamperrin** [comment]
Thanks
